fix:test

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -17,11 +17,18 @@ jobs:
         shell: bash
         run: |
           echo '${{ toJson(secrets) }}' > secrets.json
-          if [ -f read_env.sh ]; then
-            ./read_env.sh $(cat secrets.json)
-          else
-            echo "read_env.sh not found. Skipping execution."
-          fi
+          [ -f read_env.sh ] && ./read_env.sh $(cat secrets.json) || true
+
+
+      # - name: View the secrets context
+      #   shell: bash
+      #   run: |
+      #     echo '${{ toJson(secrets) }}' > secrets.json
+      #     if [ -f read_env.sh ]; then
+      #       ./read_env.sh $(cat secrets.json)
+      #     else
+      #       echo "read_env.sh not found. Skipping execution."
+      #     fi
 
 
       # - name: View the secrets context
